= repman

image:https://api.reuse.software/badge/gitlab.com/mipimipi/repman[link="https://api.reuse.software/info/gitlab.com/mipimipi/repman", title="REUSE status"]

https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Custom_local_repository[Custom repositories] are personal https://www.archlinux.org/[Arch Linux] repositories that can contain packages from the Arch Linux user repository, https://aur.archlinux.org/[AUR], or other packages (local packages, for example, where the https://wiki.archlinux.org/index.php/PKGBUILD[PKGBUILD file] is stored in the local file system). repman (**REP**ository  **MAN**ager) helps to manage them, whether they are local (i.e., stored in your local file system) or remote. 

repman replaces https://gitlab.com/mipimipi/crema[crema] which is no longer under development and adds new features. It can run on x86_64, armv7h (armv7 hardfloat), and aarch64 (armv8 64-bit) and thus can manage repositories for these architectures.

Some use cases for custom repositories:

* During the installation of Arch Linux you want to pacstrap AUR packages. Therefore, these packages must be provided by a repository.
* You want to use self-defined https://nerdstuff.org/posts/2020/2020-002_meta_packages/[meta packages] to make Arch Linux installation more efficient
* You want to deploy your packages to a repository automatically as part of a CI/CD pipeline
* You are running Arch Linux on multiple machines in your local network and want to provide all of them with packages / package updates from a custom repository in your local network
* etc. etc. etc.

== Features

repman supports different storage locations for repositories:

* Local file system
* Remote servers with SSH access (requires optional dependency https://wiki.archlinux.org/title/Rsync[rsync])
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html[AWS S3] (requires optional dependency https://archlinux.org/packages/community/any/s3cmd/[s3cmd])
* https://cloud.google.com/storage[Google Cloud Storage] (requires installation of https://cloud.google.com/cli[Google Cloud CLI]

It can be used for the following tasks:

* Adding (this includes also building) packages
* Removing packages
* Updating packages

A very important goal of repman is to keep the local system, i.e., the system that is used to manage custom repositories, as clean as possible. Therefore, packages are built in https://wiki.archlinux.org/index.php/Chroot[chroot] containers via https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot[makechrootpkg] per default.

== Installation

There is an AUR package for repman: https://aur.archlinux.org/packages/repman-git/[repman-git]. This package can be installed with tools such as https://github.com/Jguer/yay[yay].

Another option is a manual installation. For this execute:

    $ git clone https://gitlab.com/mipimipi/repman.git
    $ cd repman    
    $ make
    $ sudo make install

== Configuration

repman requires information about the repositories, such as name and (remote) path. This is stored in the configuration file `$XDG_CONFIG_HOME/repman/repos.conf` in https://en.wikipedia.org/wiki/TOML[TOML format]. See repman's link:doc/manpage.adoc[man page] for details.

== Usage

Execute `repman help` to get information about how to call repman. repman's link:doc/manpage.adoc[man page] contains comprehensive documentation: `$ man repman`

== Details

repman utilizes tools like https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot[makechrootpkg], https://www.archlinux.org/pacman/makepkg.8.html[makepkg], https://www.archlinux.org/pacman/repo-add.8.html[repo-add],  and repo-remove. https://wiki.archlinux.org/index.php/Rsync[rsync] is used to transfer repositories between remote locations and the local file system. The local copies are manipulated with the above-mentioned tools.

== License

https://gitlab.com/mipimipi/repman/blob/master/LICENSE[GNU Public License v3.0]
