# SPDX-FileCopyrightText: 2019-2024 Michael Picht <mipi@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "repman"
SPDX-PackageSupplier = "Michael Picht <mipi@fsfe.org>"
SPDX-PackageDownloadLocation = "gitlab.com/mipimipi/repman"

[[annotations]]
path = [".gitignore", "repman-all", "cfg/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2024 Michael Picht <mipi@fsfe.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
